command:
  name: go
  arg:
    - run
    - ./main.go
path:
  - .
  - name: model
  - name: pkg
    include:
      - utils*
      - config.go
    exclude:
      - const.go
exclude:
  - vendor
  - '*_test.go'
extension:
  - go
interval: 2