build:
  dir: .
  file: main.go
path:
  - name: model
  - name: pkg
    file:
      - pkg.go
      - const.go
    dir:
      - name: utils
    exclude:
      - const.go
exclude:
  dir:
    - vendor
  file:
    - '*_test.go'
extension:
  - go
ignore_test: true
interval: 2