command:
  name: go
  args:
    - run
    - ./main.go
path:
  - name: .
    include:
      - main.go
  - name: model
  - name: pkg
    dir:
      - name: utils
    include:
      - pkg.go
    exclude:
      - const.go
exclude:
  dir:
    - vendor
  file:
    - '*_test.go'
extension:
  - go
interval: 2