command:
  name: go
  args: 
    - run
    - ./main.go
path:
  - name: model
  - name: pkg
    dir:
      - name: utils
    exclude:
      - const.go
exclude:
  dir:
    - vendor
  file:
    - '*_test.go'
extension:
  - go
interval: 2