build:
  env:
    GO111MODULE: on
  target: main.go
  output: /tmp/app
  arg:
    - -race
    - -v
    - -p: 2
  before:
    - echo Before Build      hook
  after:
    - echo After Callback
path:
  - .
  - name: no_exists_dir
  - name: model
  - name: pkg
    include:
      - utils*
      - config.go
    exclude:
      - const.go
exclude:
  - vendor
  - '*_test.go'
extension:
  - go
interval: 2